spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.115.151.17:6000/znfx?useSSL=false&serverTimezone=UTC
    username: root
    password: root
  data:
    mongodb:
      uri: mongodb://114.115.151.17:6001
      database: znfx